apps/logreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'login'),
    url(r'^process$', views.process, name = 'process'),
    url(r'^logout$', views.logout, name = 'logout')
]

apps/wishlists/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^create$', views.create, name='create'),
    url(r'^add$', views.add, name='add'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^addproduct/(?P<id>\d+)$', views.addproduct, name='addproduct'),
    url(r'^removeproduct/(?P<id>\d+)$', views.removeproduct, name='removeproduct'),
    url(r'^product/(?P<id>\d+)$', views.product, name='product'),
]

wishlist/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.logreg.urls', namespace = 'login')),
    url(r'^wishlists/', include('apps.wishlists.urls', namespace = 'wishlist'))

]

apps/wishlists/models.py
from __future__ import unicode_literals
from ..logreg.models import User
from django.db import models

# Create your models here.
#product list
class Product(models.Model):
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    adder = models.ForeignKey(User, on_delete=models.CASCADE, related_name='madeproduct')

apps/wishlists/templates/views.py
from django.shortcuts import render, redirect
from ..login.models import User
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Product

def dashboard(request):
    if 'id' not in request.session:
        return redirect(reverse('login:index'))
    user = User.usrMgr.get(id=request.session['id'])
    context = {
        'products': user.product_set.all().exclude(adder__id=request.session['id']),
        'myproducts': Product.objects.filter(adder__id=request.session['id']),
        'otherproducts': Product.objects.exclude(users__id=request.session['id']),
    }
    return render(request, 'wishlists/dashboard.html', context)

def create(request):
    return render(request, 'wishlists/adding.html')

def add(request):
    if request.method != 'POST':
        return redirect(reverse('wishlists:dashboard'))
    pname = request.POST['product']
    if len(pname) < 3:
        messages.error('Product name must be longer than 3')
        return redirect(reverse('wishlists:create'))
    user = User.objects.get(id=request.session['id'])
    try:
        p = Product.objects.get(name=pname)
    except:
        p = Product.objects.create(name=pname, adder=user)
    p.users.add(user)
    return redirect(reverse('wishlists:dashboard'))

def delete(request, id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlists:dashboard'))
    #only creator can delete the item
    if p.adder.id != request.session['id']:
        return redirect(reverse('wishlists:dashboard'))
    p.delete()
    return redirect(reverse('wishlists:dashboard'))

def addproduct(request, id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlists:dashboard'))
    user = User.objects.get(id=request.session['id'])
    p.users.add(user)
    return redirect(reverse('wishlists:dashboard'))

def removeproduct(request, id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlists:dashboard'))
    user = User.objects.get(id=request.session['id'])
    p.users.remove(user)
    return redirect(reverse('wishlists:dashboard'))

def product(request, id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlists:dashboard'))
    context = {
    'users': p.users.all(),
    'name': p.name,
    }
    return render(request, 'wishlists/product.html', context)

apps/wishlists/views.py
from django.shortcuts import render, redirect
from .models import Product
from ..logreg.models import User
from django.core.urlresolvers import reverse
from django.contrib import messages


def dashboard(request):
    if 'id' not in request.session:
        return redirect(reverse('login:index'))
    user = User.usrMgr.get(id=request.session['id'])
    context = {
        'products': user.product_set.all().exclude(adder__id=request.session['id']),
        'myproducts': Product.objects.filter(adder__id=request.session['id']),
        'otherproducts': Product.objects.exclude(users__id=request.session['id']),
    }
    return render(request, 'wishlists/dashboard.html', context)

def create(request):
    return render(request, 'wishlists/adding.html')

def add(request):
    if request.method != 'POST':
        return redirect(reverse('wishlists:dashboard'))
    pname = request.POST['product']
    if len(pname) < 3:
        messages.error('Product name must be longer than 3')
        return redirect(reverse('wishlists:create'))
    user = User.usrMgr.get(id=request.session['id'])
    try:
        p = Product.objects.get(name=pname)
    except:
        p = Product.objects.create(name=pname, adder=user)
    p.users.add(user)
    return redirect(reverse('wishlist:dashboard'))

def delete(request, id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlist:dashboard'))
    #only creator can delete the item
    if p.adder.id != request.session['id']:
        return redirect(reverse('wishlist:dashboard'))
    p.delete()
    return redirect(reverse('wishlist:dashboard'))

def addproduct(request, id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlist:dashboard'))
    user = User.objects.get(id=request.session['id'])
    p.users.add(user)
    return redirect(reverse('wishlist:dashboard'))

def removeproduct(request, id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlist:dashboard'))
    user = User.objects.get(id=request.session['id'])
    p.users.remove(user)
    return redirect(reverse('wishlist:dashboard'))

def product(request, id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlist:dashboard'))
    context = {
    'users': p.users.all(),
    'name': p.name,
    }
    return render(request, 'wishlists/product.html', context)
from django.shortcuts import render

# Create your views here.

apps/wishlists/templates/wishlists/adding.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'wishlists/css/style_a.css' %}" media="screen">
    </head>
    <body>
        <h1>Create a New Wish List Item</h1>
        <div id="header">
            <a href="{% url 'wishlist:dashboard' %}">Home</a>
            <a href="{% url 'login:logout' %}">Logout</a>
        </div>
        <form action="{% url 'wishlist:add' %}" method="post">

            {% csrf_token %}
            {% for message in messages %}
                <p>{{message}}</p>
            {% endfor %}
            <p>Item/Product: <input type="text" name="product"></p>

            <input type="submit" value="Add">
        </form>
    </body>
</html>

apps/wishlists/templates/wishlists/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>My Wish List</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'wishlists/css/style_d.css' %}" media="screen">
    </head>
    <body>
        <div id="header">
            <h1>Hello, {{user.name}}!</h1>
            <a id="logout" href="{% url 'login:logout' %}">Logout</a>
        </div>
        <div id="uwishlist">
            <h4>Your Wish List:</h4>
            <table>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
                {% for product in products %}
                <tr class='border'>
                    <td><a href="{% url 'wishlist:product' id=product.id %}">{{product.name}}</a></td>
                    <td>{{product.adder.name}}</td>
                    <td>{{product.created_at|date:"M d, Y"}}</td>
                    <td><a href="{% url 'wishlist:removeproduct' id=product.id%}">Remove from my wishlist</a></td>
                </tr>
                {% endfor %}
                {% for product in myproducts %}
                <tr class='border'>
                    <td><a href="{% url 'wishlist:product' id=product.id %}">{{product.name}}</a></td>
                    <td>{{product.adder.name}}</td>
                    <td>{{product.created_at|date:"M d, Y"}}</td>
                    <td><a href="{% url 'wishlist:delete' id=product.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </table>

        </div>
        <div id="owishlist">
            <h4>Other Users' Wish List:</h4>
            <table>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
                {% for product in otherproducts %}
                <tr class='border'>
                    <td><a href="{% url 'wishlist:product' id=product.id %}">{{product.name}}</a></td>
                    <td>{{product.adder.name}}</td>
                    <td>{{product.created_at|date:"M d, Y"}}</td>
                    <td><a href="{% url 'wishlist:addproduct' id=product.id %}">Add to my wishlists</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <a id="create" href="{% url 'wishlist:create' %}">Add Item</a>
    </body>
</html>

apps/wishlists/templates/wishlists/product.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{name}}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'wishlist/css/create.css' %}" media="screen">
    </head>
    <body>
        <h1>{{name}}</h1>
        <div id="header">
            <a href="{% url 'wishlist:dashboard' %}">Home</a>
            <a href="{% url 'login:logout' %}">Logout</a>
        </div>
        <p>
            Users who added this product/item under their wish list:
        </p>

        {% for user in users%}
            <p>{{user.name}}</p>
        {% endfor %}
    </body>
</html>